name: Docker Image 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login DockerHub
      run: |
        echo ",'X=2d?cc=:>6EaMu'" | docker login -u nerurodeomo --password-stdin
