name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo 'dckr_pat_KQAx1hXN4UjM2HmLLKzXPfGSmtA' | docker login -u kbamunuarachchi0331 --password-stdin

      - name: Build the Docker image
        run: docker build -t kbamunuarachchi0331/coursework-group_95:latest .

      - name: Push to DockerHub
        run: docker push kbamunuarachchi0331/coursework-group_95:latest
